-- ************************************************************************************************ --
-- ----------------------------- Global Structure ------------------------------------------------- --
-- ************************************************************************************************ --

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ************************************************************************************************ --
-- ----------------------------- Drop Existing Tab ------------------------------------------------ --
-- ************************************************************************************************ --

-- /!\ you will loose all your data in database ! /!\ --

DROP TABLE IF EXISTS `T_LINK_PP_S`;
DROP TABLE IF EXISTS `T_PROJECT_PART`;
DROP TABLE IF EXISTS `T_STOCK`;
DROP TABLE IF EXISTS `T_SUB_TASK`;
DROP TABLE IF EXISTS `T_WORK_ORDER`;
DROP TABLE IF EXISTS `T_PROJECT`;
DROP TABLE IF EXISTS `T_HELICOPTER`;
DROP TABLE IF EXISTS `T_ENGINE`;
DROP TABLE IF EXISTS `T_CUSTOMER`;
DROP TABLE IF EXISTS `T_USER`;
DROP TABLE IF EXISTS `T_LINK_GP_GST`;
DROP TABLE IF EXISTS `T_GENERIC_PART`;
DROP TABLE IF EXISTS `T_GENERIC_SUB_TASK`;
DROP TABLE IF EXISTS `T_MANUAL`;
DROP TABLE IF EXISTS `T_GENERIC_AIRCRAFT`;
DROP TABLE IF EXISTS `T_FILE`;
DROP TABLE IF EXISTS `T_LOG`;
DROP TABLE IF EXISTS `T_VENDOR`;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `File`
-- 1
-- ---

CREATE TABLE `T_FILE` (
  `F_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `F_NAME` VARCHAR(255) NOT NULL,
  `F_DIRECTORY` VARCHAR(64) NOT NULL,
  `F_SIZE` INT NOT NULL,
  `F_FORMAT` VARCHAR(10) NOT NULL ,
  `F_MD5` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`F_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Generic_Aircraft`
-- 2
-- ---
    
CREATE TABLE `T_GENERIC_AIRCRAFT` (
  `GA_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `GA_NAME` VARCHAR(32) NOT NULL,
  `GA_CONSTRUCTOR` VARCHAR(32) NOT NULL,
  `GA_TYPE` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`GA_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Manual`
-- 3
-- ---
    
CREATE TABLE `T_MANUAL` (
  `M_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `M_ID_GA` INT NOT NULL,
  `M_ID_MANUAL` INT NULL DEFAULT NULL,
  `M_NAME` VARCHAR(128) NOT NULL,
  `M_REFERENCE` VARCHAR(32) NOT NULL,
  `M_DESCRIPTION` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`M_ID`),
  CONSTRAINT FK_M_GA FOREIGN KEY (M_ID_GA) REFERENCES `T_GENERIC_AIRCRAFT` (`GA_ID`),
  CONSTRAINT FK_M_F_MANUAL FOREIGN KEY (M_ID_MANUAL) REFERENCES `T_FILE` (`F_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Generic_Sub_Task`
-- 5
-- ---
    
CREATE TABLE `T_GENERIC_SUB_TASK` (
  `GST_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `GST_ID_M` INTEGER NOT NULL,
  `GST_NUMBER` VARCHAR(16) NOT NULL,
  `GST_DESCRIPTION` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`GST_ID`),
  KEY (`GST_ID_M`),
  CONSTRAINT FK_GST_M FOREIGN KEY (GST_ID_M) REFERENCES `T_MANUAL` (`M_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Generic_Part`
-- 6
-- ---
    
CREATE TABLE `T_GENERIC_PART` (
  `GP_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `GP_NUMBER` MEDIUMTEXT NOT NULL,
  `GP_NAME` VARCHAR(32) NOT NULL,
  `GP_TYPE` VARCHAR(16) NULL DEFAULT NULL,
  `GP_LOCATION` MEDIUMTEXT NULL DEFAULT NULL,
  `GP_DESCRIPTION` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`GP_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Link_GP_GST` (Link between Generic Part and Generic Sub-Task)
-- 7
-- ---

CREATE TABLE `T_LINK_GP_GST` (
  `LGG_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `LGG_ID_GP` INTEGER NOT NULL,
  `LGG_ID_GST` INTEGER NOT NULL,
  `LGG_QTY` INTEGER NOT NULL,
  `LGG_IPC` CHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`LGG_ID`),
  UNIQUE(`LGG_ID_GP`, `LGG_ID_GST`, `LGG_IPC`),
  CONSTRAINT FK_LGG_GP FOREIGN KEY (LGG_ID_GP) REFERENCES `T_GENERIC_PART` (`GP_ID`),
  CONSTRAINT FK_LGG_GST FOREIGN KEY (LGG_ID_GST) REFERENCES `T_GENERIC_SUB_TASK` (`GST_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `User`
-- 8
-- ---
    
CREATE TABLE `T_USER` (
  `U_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `U_NAME` VARCHAR(16) NOT NULL,
  `U_PASSWORD` VARCHAR(64) NOT NULL,
  `U_STATUS` INTEGER NOT NULL DEFAULT 4,
  `U_CODE` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`U_ID`),
  UNIQUE KEY (`U_NAME`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Customer`
-- 9
-- ---
    
CREATE TABLE `T_CUSTOMER` (
  `C_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `C_NAME` VARCHAR(32) NOT NULL,
  `C_PHONE` VARCHAR(20) NULL DEFAULT NULL,
  `C_MAIL` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`C_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Engine`
-- 10
-- ---
    
CREATE TABLE `T_ENGINE` (
  `E_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `E_ID_GA` INT NOT NULL,
  `E_ID_LOG_BOOK` INT NULL DEFAULT NULL,
  `E_SERIAL` VARCHAR(32) NULL DEFAULT NULL,
  `E_NAME` VARCHAR(32) NULL DEFAULT NULL,
  `E_TYPE` VARCHAR(32) NULL DEFAULT NULL,
  `E_TIME` DECIMAL(10,2) NULL DEFAULT NULL,
  `E_NG_CYCLE` DECIMAL(10,1) NULL DEFAULT NULL,
  `E_NF_CYCLE` DECIMAL(10,1) NULL DEFAULT NULL,
  PRIMARY KEY (`E_ID`),
  CONSTRAINT FK_E_GA FOREIGN KEY (E_ID_GA) REFERENCES `T_GENERIC_AIRCRAFT` (`GA_ID`),
  CONSTRAINT FK_E_F_LB FOREIGN KEY (E_ID_LOG_BOOK) REFERENCES `T_FILE` (`F_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Helicopter`
-- 11
-- ---

    
CREATE TABLE `T_HELICOPTER` (
  `H_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `H_ID_GA` INTEGER NOT NULL,
  `H_ID_E1` INTEGER NULL DEFAULT NULL,
  `H_ID_E2` INTEGER NULL DEFAULT NULL,
  `H_ID_LOG_BOOK` INT NULL DEFAULT NULL,
  `H_ID_STATUS_SHEET` INT NULL DEFAULT NULL,
  `H_SERIAL` VARCHAR(32) NULL DEFAULT NULL,
  `H_TIME` DECIMAL(10,2) NULL DEFAULT NULL,
  `H_LANDING` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`H_ID`),
  UNIQUE KEY (`H_ID_E1`),
  UNIQUE KEY (`H_ID_E2`),
  CONSTRAINT FK_H_GA FOREIGN KEY (H_ID_GA) REFERENCES `T_GENERIC_AIRCRAFT` (`GA_ID`),
  CONSTRAINT FK_H_E1 FOREIGN KEY (H_ID_E1) REFERENCES `T_ENGINE` (`E_ID`) ON DELETE SET NULL,
  CONSTRAINT FK_H_E2 FOREIGN KEY (H_ID_E2) REFERENCES `T_ENGINE` (`E_ID`) ON DELETE SET NULL,
  CONSTRAINT FK_H_F_LB FOREIGN KEY (H_ID_LOG_BOOK) REFERENCES `T_FILE` (`F_ID`),
  CONSTRAINT FK_H_F_SS FOREIGN KEY (H_ID_STATUS_SHEET) REFERENCES `T_FILE` (`F_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Project`
-- 12
-- ---
    
CREATE TABLE `T_PROJECT` (
  `P_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `P_ID_C` INTEGER NOT NULL,
  `P_ID_H` INTEGER NOT NULL,
  `P_NAME` VARCHAR(32) NOT NULL,
  `P_OPENED_DATE` DATE NOT NULL,
  `P_CLOSED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`P_ID`),
  UNIQUE KEY (`P_ID_H`),
  CONSTRAINT FK_P_C FOREIGN KEY (P_ID_C) REFERENCES `T_CUSTOMER` (`C_ID`),
  CONSTRAINT FK_P_H FOREIGN KEY (P_ID_H) REFERENCES `T_HELICOPTER` (`H_ID`) ON DELETE CASCADE
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Work_Order`
-- 13
-- ---
    
CREATE TABLE `T_WORK_ORDER` (
  `WO_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `WO_ID_H` INTEGER NOT NULL,
  `WO_NAME` VARCHAR(256) NULL DEFAULT NULL,
  `WO_OPENED_DATE` DATE NOT NULL,
  `WO_CLOSED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`WO_ID`),
  CONSTRAINT FK_WO_H FOREIGN KEY (WO_ID_H) REFERENCES `T_HELICOPTER` (`H_ID`) ON DELETE CASCADE
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Sub_Task`
-- 14
-- ---
    
CREATE TABLE `T_SUB_TASK` (
  `ST_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `ST_ID_WO` INTEGER NOT NULL,
  `ST_ID_GST` INTEGER NOT NULL,
  `ST_ID_U_PERFORMER` INTEGER NULL DEFAULT NULL,
  `ST_ID_U_RELEASER` INTEGER NULL DEFAULT NULL,
  `ST_REFERENCE` VARCHAR(32) NULL DEFAULT NULL,
  `ST_WORK_REQUIRED` MEDIUMTEXT NULL DEFAULT NULL,
  `ST_RECTIFICATION_DETAILS` MEDIUMTEXT NULL DEFAULT NULL,
  `ST_IN_SOW` VARCHAR(3) NOT NULL DEFAULT 'no',
  `ST_APPROVED_DATE` DATE NULL DEFAULT NULL,
  `ST_PERFORM_DATE` DATE NULL DEFAULT NULL,
  `ST_RELEASE_DATE` DATE NULL DEFAULT NULL,
  `ST_PRICE_QUOTE` DECIMAL(10,2) NULL DEFAULT NULL,
  `ST_ACCURRENCY` VARCHAR(8) NULL DEFAULT NULL,
  `ST_S_REFERENCES` MEDIUMTEXT NULL DEFAULT NULL,
  `ST_S_REMOVE` MEDIUMTEXT NULL DEFAULT NULL,
  `ST_S_INSTALL` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ST_ID`),
  KEY (`ST_ID_WO`),
  CONSTRAINT FK_ST_WO FOREIGN KEY (ST_ID_WO) REFERENCES `T_WORK_ORDER` (`WO_ID`) ON DELETE CASCADE,
  CONSTRAINT FK_ST_GST FOREIGN KEY (ST_ID_GST) REFERENCES `T_GENERIC_SUB_TASK` (`GST_ID`),
  CONSTRAINT FK_ST_U_PERFORMER FOREIGN KEY (ST_ID_U_PERFORMER) REFERENCES `T_USER` (`U_ID`),
  CONSTRAINT FK_ST_U_RELEASER FOREIGN KEY (ST_ID_U_RELEASER) REFERENCES `T_USER` (`U_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Stock`
-- 15
-- ---
    
CREATE TABLE `T_STOCK` (
  `S_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `S_ID_GP` INTEGER NOT NULL,
  `S_ID_PURCHASE_ORDER` INT NULL DEFAULT NULL,
  `S_ID_ARC` INT NULL DEFAULT NULL,
  `S_INDEX_PN` INT NOT NULL DEFAULT 0,
  `S_SERIAL` VARCHAR(128) NULL DEFAULT NULL,
  `S_ARC_NAME` VARCHAR(255) NULL DEFAULT NULL,
  `S_PO_NAME` VARCHAR(255) NOT NULL,
  `S_QUANTITY_IN` INTEGER NULL DEFAULT NULL,
  `S_QUANTITY_NUMBER` INTEGER NOT NULL DEFAULT 1,
  `S_RECEIVED` VARCHAR(3) NOT NULL DEFAULT 'no',
  `S_RECEIVED_DATE` DATE NULL DEFAULT NULL,
  `S_EXPIRATION_DATE` DATE NULL DEFAULT NULL,
  `S_PRICE` DECIMAL(10,2) NULL DEFAULT NULL,
  `S_ACCURENCY` VARCHAR(8) NULL DEFAULT NULL,
  `S_VENDOR` VARCHAR(128) NULL DEFAULT NULL,
  `S_COMMENT` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`S_ID`),
  KEY (`S_ID_GP`),
  CONSTRAINT FK_S_GP FOREIGN KEY (S_ID_GP) REFERENCES `T_GENERIC_PART` (`GP_ID`),
  CONSTRAINT FK_S_F_PO FOREIGN KEY (S_ID_PURCHASE_ORDER) REFERENCES `T_FILE` (`F_ID`),
  CONSTRAINT FK_S_F_ARC FOREIGN KEY (S_ID_ARC) REFERENCES `T_FILE` (`F_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Project Part`
-- 16
-- ---

CREATE TABLE `T_PROJECT_PART` (
  `PP_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `PP_ID_ST` INTEGER NOT NULL,
  `PP_ID_GP` INTEGER NOT NULL,
  `PP_ID_USER` INTEGER NOT NULL,
  `PP_IPC` VARCHAR(32) NULL DEFAULT NULL,
  `PP_STATUS` VARCHAR(8),
  `PP_DEFECT` VARCHAR(3) NOT NULL DEFAULT 'no',
  `PP_VALIDATED` VARCHAR(3) NOT NULL DEFAULT 'no',
  `PP_QUANTITY_REQUESTED` INTEGER NOT NULL DEFAULT 1,
  `PP_REQUESTED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`PP_ID`),
  CONSTRAINT FK_PP_ST FOREIGN KEY (PP_ID_ST) REFERENCES `T_SUB_TASK` (`ST_ID`),
  CONSTRAINT FK_PP_GP FOREIGN KEY (PP_ID_GP) REFERENCES `T_GENERIC_PART` (`GP_ID`),
  CONSTRAINT FK_PP_U FOREIGN KEY (PP_ID_USER) REFERENCES `T_USER` (`U_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Link_PP_S` (Link between Project Part and Stock Part)
-- 17
-- ---

CREATE TABLE `T_LINK_PP_S` (
  `LPS_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `LPS_ID_PP` INTEGER NOT NULL,
  `LPS_ID_S` INTEGER NOT NULL,
  `LPS_QUANTITY_NUMBER` INTEGER NOT NULL,
  `LPS_DATE_OUT` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`LPS_ID`),
  UNIQUE(`LPS_ID_PP`,`LPS_ID_S`),
  CONSTRAINT FK_LPS_PP FOREIGN KEY (LPS_ID_PP) REFERENCES `T_PROJECT_PART` (`PP_ID`),
  CONSTRAINT FK_LPS_S FOREIGN KEY (LPS_ID_S) REFERENCES `T_STOCK` (`S_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Logs` (Table of INSERT / UPDATE / DELETE logs)
-- 17
-- ---

CREATE TABLE `T_LOG` (
  `LOG_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `LOG_EVENT_TIME` DATETIME NOT NULL,
  `LOG_USER` VARCHAR(64) NOT NULL,
  `LOG_TYPE` VARCHAR(16) NOT NULL,
  `LOG_ID_TARGET` INT NOT NULL,
  `LOG_FUNCTION` VARCHAR(64) NOT NULL,
  `LOG_PARAMETERS` LONGTEXT NULL DEFAULT NULL,
  `LOG_INFO` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Vendors` (Table of Vendors for RFQ and PO)
-- 17
-- ---

CREATE TABLE `T_VENDOR` (
  `V_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `V_NAME` VARCHAR(128) NULL DEFAULT NULL,
  `V_ADDRESS` VARCHAR(512) NULL DEFAULT NULL,
  `V_CITY` VARCHAR(128) NULL DEFAULT NULL,
  `V_COUNTRY` VARCHAR(128) NULL DEFAULT NULL,
  `V_PHONE` VARCHAR(16) NULL DEFAULT NULL,
  `V_MAIL` VARCHAR(128) NULL DEFAULT NULL,
  `V_CONTACT` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`V_ID`)
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `Recorded Work` (Table of Recorded Works)
-- 18
-- ---

CREATE TABLE `T_RECORDED_WORK` (
  `RW_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `RW_ID_ST` INT NULL DEFAULT NULL,
  `RW_DESCRIPTION` MEDIUMTEXT NULL DEFAULT NULL,
  `RW_TOTAL_MIN` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`RW_ID`),
  CONSTRAINT FK_RW_ST FOREIGN KEY (RW_ID_ST) REFERENCES `T_SUB_TASK` (`ST_ID`) ON DELETE CASCADE
)ENGINE=innodb;

-- -------------------------------------------------------------------------------------------------------------------------------------------- --
-- Table `User Work` (Table of Recorded User Work)
-- 19
-- ---

CREATE TABLE `T_USER_WORK` (
  `UW_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `UW_ID_RW` INT NOT NULL,
  `UW_ID_U` INT NOT NULL,
  `UW_DATETIME_BEGIN` DATETIME NOT NULL,
  `UW_DATETIME_END` DATETIME NULL DEFAULT NULL,
  `UW_TOTAL_MIN` INT NULL DEFAULT NULL,
  PRIMARY KEY (`UW_ID`),
  CONSTRAINT FK_UW_RW FOREIGN KEY (UW_ID_RW) REFERENCES `T_RECORDED_WORK` (`RW_ID`) ON DELETE CASCADE,
  CONSTRAINT FK_UW_U FOREIGN KEY (UW_ID_U) REFERENCES `T_USER` (`U_ID`)
)ENGINE=innodb;

-- NB : PP_STATUS can be : request, ordered, issue

-- ************************************************************************************************ --
-- ----------------------------- Table Properties ------------------------------------------------- --
-- ************************************************************************************************ --

-- ALTER TABLE `Project` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Customer` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Helicopter` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Engine` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Manual` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Work_Order` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Sub_Task` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Stock` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `User` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Generic_Part` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Generic_Sub_Task` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `Generic_Aircraft` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ************************************************************************************************ --
-- ----------------------------- Dafault Vendor List ---------------------------------------------- --
-- ************************************************************************************************ --

-- 0
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ASIA TENGGARA AVIATION SERVICES','LOT 10, HELICOPTER CENTRE SULTAN ABDUL AZIZ SHAH AIRPORT', '47200 SUBANG, SELANGOR', 'MALAYSIA', '0178183337', NULL,'GOBI RAJA AYAVOO');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AEROTEX INTERNATIONAL','107 HILLSIDE DRIVE', 'TX 75057 LEWISVILLE', 'USA', '+1 972-353-4100	', NULL,'WILLIE HUTSON');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ASIA AERO TECHNIC SDN BHD',NULL, '47200 SUBANG, SELANGOT', 'MALAYSIA', '03-7842 2881', NULL,'FRANK LOO	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AIR MYANMAR AVIATION','SEASON HOTEL, AIRPORT ESTATE', 'MIGALARDON TOWNSHIP', 'YANGON, MYANMAR', '+959512001	', NULL,'KHIN MUANG MYINT	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AMUR FINANCE COMPANY INC',NULL, NULL, NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AEROSPACE ALLIANCE GROUP','CITA DAMANSARA A-10-2 A, JALAN PJU 3/27', '47810 SUNWAY DAMANSARA, PJ SELANGOR', 'MALAYSIA', '+601222133449', NULL,' Alain Kedzierski	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ASIAN AEROSPACE SERVICES Ltd','23RD FLOOR CHAMAN PHENJATI BUSINESS CENTER', '10310 BANGKOK', 'THAILAND', '+66818326957', NULL,'Hubert Trunzer (M.D.)');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AEROFLIGHT HOLDINGS LIMITED','PRIVATE BAG 14, 690, HARVARD LANE, ARDMORE AIRPORT', 'PAPAKURA 1703 AUCKLAND', 'NEW ZELAND', '+6492998900	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ADVANCED HELICOPTERS','17986 COUNTY ROAD 94B', 'WOODLAND CALIFORNIA 95695', 'USA','+15306697115', NULL,' Helen	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AIR MYANMAR AVIATION','SESSON HOTEL, AIRPORT ESTATE', 'MIGALARDON TOWNSHIP', 'MYANMAR', '+9595120001', NULL,NULL);
-- 10
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AIR MEDIC', NULL, NULL, NULL, NULL, NULL,'Guy Tremblay');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AVIATION MANAGEMENT','2964 NW 60TH STREET', 'FORT LAUDERDALE FL 33309', 'USA', '+19545430400', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AMUR HELICOPTER FINANCIAL SERVICES',NULL, NULL, NULL, '+19177175687', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AMUR HFS LLC c/o LLOYD, HELICOPTERS ASIA PTE. LTD','1 KIM SENG PROMENADE', '09-03 GREAT WORLD CITY EAST TOWER', 'SINGAPORE 237994', '+6562216422', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AIRCOM TECHNOLOGIES INC','354 WALLACE STREET', 'HUDSON, QC. JOP 1HO', 'CANADA', '+14504582252	', NULL,'Bill Caban	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ASIA SKY GROUP','SUITE 3905, FAR EAST FINANCE CENTRE, 16 HARCOURT ROAD', 'ADMIRALITY, HONG KONG', 'HONG KONG', '+85222359278', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AURA AVIATION','BUILDING 510, CAMPBELL WAY, BIGGIN HILL AIRPORT', 'BIGGIN HILL, KENT', 'ENGLAND', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AVINCO LIMITED','5 MARINE TERRACE, DUN LAOGHAIRE', 'CO DUBLIN', 'IRELAND', '+35316637440', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AGUSTA WESTLAND MALAYSIA','DNEST AVIATION SERVICES OLD CARGO COMPLEX, SAAS INTERNATIONAL AIRPORT', 'SUBANG AIRPORT, 47200 SUBANG, SELANGOR D.E.', 'MALAYSIA', '+60378467324	', NULL,'PETER PERLOWSKI');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'BENNETT AVIONICS','16 CONCORD DRIVE', 'EAST GRANBY, CT 06026', 'USA', '001 8604081695	', NULL,'SCOTT DEHART	');
-- 20
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'BATAM AERO TECHNIC',NULL, 'BATAM', 'INDONESIA', '+628118080031', NULL,'Didier Aulet');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'BANGLA INTERNATIONAL','SUITE # B1, 1ST FLOOR, ROAD # 111, GUISHAN-2', 'DHAKA-1212', 'BANGLADESH', '+8801711563976	', NULL,' Nagmul Islam');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'C&M CHILE','AV. LAS CONDES 7345, LAS CONDES', '756094 SANTIAGO', 'CHILE', '+5623743166', NULL,'Eduardo Barriga');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'CAPITAL GROUP NZ',NULL, NULL, 'NEW ZEALAND', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'PT CIPTA',NULL, NULL, NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'DAL',NULL, NULL, NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'DIRECT HELICOPTER','14 NEW LAKESHORE RD UNIT 24', 'PORT DOVER, ONTARIO', 'CANADA N0A1N8', '+15194103930	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'DL',NULL, NULL, NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ENEGRA SERVICES LTD','LEVEL 14 SUITES 2 MENARA IMC, 8 JALAN SULTAN ISMAIL', '50250 KUALA LUMPUR', 'MALAYSIA', '03-2777 0829	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AIRBUS HELICOPTERS MALAYSIA','HELICOPTER CENTRE, MALAYSIA INTERNATIONAL AEROSPACE CENTRE', '47200 SUBANG, SELANGOR', 'MALAYSIA', '+603-78483408	', NULL,NULL);
-- 30
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'AIRBUS PHILIPPINES, INC','PADC Hangar No.2 Manila Domestic Airport', 'Pasay city, Metro Manila', 'PHILIPPINES', '+63258538861', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'EUCOPTER MAL',NULL, NULL, NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'FLYJET SDN BHD','THE MINES RESORT & GOLF CLUB, JALAN KELIKIR, MINES RESORT CITY', '43300 SERI KEMBAGAN, SELANGOR DARUL, EHSAN', 'MALAYSIA', '60389432288', NULL,'Azha Jalil');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'FINANCE CHARGE',NULL, NULL, NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'GALAXY AEROSPACE','SUITE 6-2B, UKAY BOULEVARD, JLN LINGKARAN TENGAH DUA, HULU KELANG', '68000 AMPANG, SELANGOR', 'MALAYSIA', '+603-7846-7004', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'GLOBAL TURBINE ASIA SDN BHD','SKYPARK SUBANG TERMINAL,	SULTAN ABDUL AZIZ SHAH AIRPORT', '47200 SUBANG, SELANGOR', 'MALAYSIA', '+603-7846-7004	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'GLOBAL HELICOPTERS (M) SDN','OFF JALAN GOMBAK', '53000 KUALA LUMPUR', 'MALAYSIA', NULL, NULL,'DATO JOHARI BIN HARUN');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'GADING KASTURI SDN BHD','6-2B UKAY BOULEVARD, JALAN LINGARAN TENGAH DUA, HULU KELANG', '68000 AMAPANG, SELANGOR, DARUL EHSAN', 'MALAYSIA', '+60341626226', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'GLORY INTERNATIONAL	TRADING CO LTD(USD)','N0.11 (A) KHAPAUNG STREET HLAING', 'TOWNSHIP YANGON', 'MYANMAR', '(95-1)501558', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'NAVIATOR SDN BHD','LOT 561 JALAN PERSIARAN SUBANG 3 OFF JLN PERSIARAN SUBANG IN', 'SUBANG JAYA, SELANGOR 47610', 'MALAYSIA', '+60351924621', NULL,'Mr. Goh	');
-- 40
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'GLORY INTERNATIONAL TRADING Co, Ltd (EUR)',NULL, 'YANGOON', 'MYANMAR', NULL, NULL,'Kyaw Min Oo');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HELITHAI & ASSOCIATES','23/78 BOAT LAGOON MARINA MOO2, THEPKASATTRI ROAD, KOH KAEW A MUANG', 'PHUKET 83000', 'THAILAND', '66819262102	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HC DESIGN PT LTD','21 TAMPINES STREET 92', '528891 SINGAPORE', 'SINGAPORE', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HELIMISSION SWITZERLAND','BLEICHI 2', 'CH-9043 TROGEN', 'SWITZERLAND', '+41713437171', NULL,'ADRIAN ROMANG	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HELI SUPPORT INC','120 NE FRONTAGE RD', 'FORT COLLINS CO 80524', 'USA', '+597432577	', NULL,'Jerrel van Embricqs');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'PENN STATE MILTON S, HERSHEY MEDICAL CENTER','500 UNIVERSITY DRIVE', 'HERSHEY, PA 17033', 'CANADA', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HELIMISSION SWITZERLAND','BLEICHI 2', 'CH-9043 TROGEN', 'SWITZERLAND', '+41713437171', NULL,'ADRIAN ROMANG');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HELIPARTNER Sdn Bhd','18th Floor  18(A), UBN tower 10 Jalan P. ramlee', '50250 KUALA LUMPUR', 'MALAYSIA', '+60320701055', NULL,'Clement Gil');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HELIPOOL EUROPE GMBH','P.O BOX 94', '7417 PASPELS', 'SWITZERLAND', '+417964428244	', NULL,'Daniel Hofer	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HELI TRAM','Krabbegatan 16', '25 436 Helsingborg', 'SWEDEN', '+4702795610', NULL,NULL);
-- 50
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'Helitrades Inc','18 Terry Fox Dr., Vankleek Hill', 'Ontario', 'Canada', '+16136783027	', NULL,'Gerald Tom	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'HELICOPTERS UNLIMITED LCC','17139 Highway 90A', 'East Bernard, Texas 77435', 'USA', '+19793354552', NULL,'Steve Tanner');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'JMV TRADETECH SDN BHD','63, PERSIARAN BUNGA RAYA, LANGKAWI MALL', '07000 KUAH LANGKAWI, KEDAH DARUL AMAN', 'MALAYSIA', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'JET FINANCE GROUP LLC','One Burton Hills Bvld Ste. 215', 'Nashville, TN 37215', 'USA', NULL, NULL,'BOB Fisher');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'LEASE CORPORATION, INTERNATIONAL','10 HOE CHIANG ROAD, #10-06 KEPPEL TOWERS', 'SINGAPORE 089315', 'SINGAPORE', '+65 91540130', NULL,'LAURENT JANITZA');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'LTB Schlemann GmBh','Harburger Strasse 118', 'D-27356 Rotenburg / Wumme', 'GERMANY', '+494261960380	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'MYCOPTER AVIATION SERVICES','LOT 10 HELICOPTER CENTRE, SULTAN ABDUL AZIZ SHAH AIRPORT', '47000 SUBANG SELANGOR', 'MALAYSIE', '0193577787', NULL,'Syahrun	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'MALINDO AIRWAYS SDN BHD','E-2-03, CAPITAL 5, OASIS ARA DAMANSARA, 2 JALAN PJU 1A/7A', '47301 PETALING JAYA', NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'MYANMAR CONSULTANCY CO','No.19, Kyaik Wine Pagoda Road, Myaing Hay Wun Housing, 8 Mil', 'Mayangone Township, Yangon', 'MYANMAR', '+959257727772	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'MHS AVIATION BHD','No.18, Block H, Jln PJU 1A/3 Taipan Damansara 2, Ara Damansara', '47301, Petaling Jaya Selangor', 'MALAYSIA', '+60378428500', NULL,NULL);
-- 60
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'MOUNTAIN HELICOPTERS PVT LTD',NULL, 'KATHMANDU', 'NEPAL', '+97714111031/32', NULL,'CHANDRAMAN PUN');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'NASH AEROSTAR SERVICE SDN BHD',NULL, NULL, NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'NAV-AIDS Ltd','2955 Diab Street', 'Montreal Q.C H4S1M1', 'Canada', '+15143323077', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ONE LOGISTIC S/A','R EMILIO MALLET, 317-CJ 1110', 'SAO PAULO, SP 03320-000', 'BRAZIL', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ORIENT GLOBAL','Level 46 UOB Plaza 1 80 Raffles Place', 'Singapore 048624', 'SINGAPORE', '+656210555', NULL,'Jazz Goh');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'OCEANIA AVIATION LIMITED','Ardmore Airport', 'AUCKLAND', 'NEW ZEALAND', '+6492962644', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'TEMPEST  Oportunities Unlimited','248B PAEKAKARIKI HILL ROAD', 'PAUATANUI, PORIRUA WELLINGTON 5381, N 5381', 'NEW ZEALAND', NULL, NULL,'Bryan');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'R.A.M.S. Aviation Company Inc','8042 Clark Road', 'Plantersville, TX 77363', NULL, '+12547528381', NULL,'Jon Rankin');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'RED DIAMOND AVIATION LIMITED','ROOM403 B, EMPIRE CENTRE 68 MODY ROAD', '2017 TSIM SHA TSUI HONG KONG', 'HONG KONG', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ROTORTRADE SERVICES PTE LTD	','18A 18th floor, UBN TOWER 10, JALAN P.RAMLEE', '50250, KUALA LUMPUR', 'MALAYSIE', '+603 2026 7055', NULL,'MARCELLO CORRADO SALATI');
-- 70
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
(NULL, 'ROTORTRADE SERVICES PTE LTD	SINGAPORE','60 Paya Lebar  Road # 08-43, Paya Lebar Square', '409051 SINGAPORE', 'SINGAPORE', NULL, NULL,'MARCELLO CORRADO SALATI');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'STRATA AVIATION INDONESIA','13 MCLEAN STREET', 'TAURANGA 1330', 'NEW ZEALAND', NULL, NULL,'GLENN STEVENSON');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'SERENITY  Helicopters','1411 Airport Rd Boulder City, NV 89005', 'Boulder City', 'NEVADA', '+18088709090', NULL,'Steve Egger');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'SFS AVIATION CO LTD','26/40 12th Floor Orakam Building, Childom Road Lumpini Patumwan', 'Bangkok 10330', 'THAILAND', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'SOLAIRE SDN BHD','Terminal, 3 Gate 39, Sultan Abdul Aziz Shah Airport, Subang Airport', '47200 Subang, Selangor D.E.', 'MALAYSIA', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'SR AVIATION Sdn Bhd','Taiko Hangar Lapangan Terbang Sultan Abdul Aziz Shah', '47200 Subang Selangor', 'MALAYSIA', '+60378462788	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ST AEROSPACE','540 Airport Road, Paya Lebar', 'Singapore 539938', 'SINGAPORE', '+6564806810	', NULL,'Andy Yeo	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'SURTECH GROUP','Satmarindo Building Jl. Ampera Raya No.5', 'Jakarta 12560', 'INDONESIA', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'JAMES TAN',NULL, NULL, NULL, NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'VECTRA AVIATION','36 Paradise Road', 'Richmond, Surrey,   TW9 1SE', 'UK', '+442089482965', NULL,NULL);
-- 80
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'Vertical Integrity Limited','Suite B1, 2nd floor wing B, Cyber Tower 1', 'Ebene Cybercity, Reduit Mauritius', 'MAURITIUS', '+2304670600	', NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'VINA COPTER','Nbr 43 B, 9th Floor Nguyen Thuong Hien, Hoang Kiem', 'Hanoi', 'VIETNAM', '+84439413050', NULL,'Juha-Pekka Hoikka');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'VINACOPTER LIMITED','42/F Central Plaza, 18 Habour road', 'Wanchai, Hongkong', 'HONGKONG', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'VERTICAL SOLUTIONS','5018 47A Avenue Delta', 'British Comumbia', 'Canada V4K 1T8', '+16045629191', NULL,'Kevin Mccart');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'Vertical Lift sdn Bhd','Unit C-106 Bayshere Park Apt. Jalan Pantai Luak', '98000 MIRI, Sarawak', 'MALAYSIA', '+60128040696', NULL,'Henrik');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'WILMAR AIR Pte Ltd','56 NEIL ROAD', 'SINGAPORE 088830', 'SINGAPORE', '+60127851640', NULL,'ADRIAN GEORGE	');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'WISDOM UNITY PTE LTD','FLAT B, 15/F VALIANT COMMERCIAL BUILDINGS, 22-24 PRAT AVENUE', 'TSIM SHA TSUI, KOWLOON HONGKONG', 'HONGKONG', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'WESTSTAR AVIATION SERVICES SDN BHD','LEVEL 8, MENARA WESTAR, DATARAN WESTSTAR', '68000 AMPANG, SELANGOR', 'MALAYSIA', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'WISDOM UNITY PTE LTD','FLATB, 15/F VALIANT COMMERCIAL BUILDING, 22-24 PRAT AVENUE, TSIM SHA TSUI', 'KOWLOON HONGKONG', 'HONGKONG', NULL, NULL,NULL);
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ZETRO Aerospace Corporation','Jalan Lapangan Terbang', 'Subang, 4000 Shah Alam, Selangor', 'MALAYSIA', '+60378430856', NULL,'Tengku Affandy');
-- 90
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'ECC LEASING COMPANY LIMITED','202 Q HOUSE 76 FURZE ROAD', 'SANDYFORD, DUBLIN 18, D18 V IK5', 'IRELAND', NULL, NULL,'ANDRE LUIZ LEITE');
INSERT INTO `T_VENDOR` (`V_ID`, `V_NAME`, `V_ADDRESS`, `V_CITY`, `V_COUNTRY`, `V_PHONE`, `V_MAIL`, `V_CONTACT`) VALUES
  (NULL, 'GENERAL DYNAMIC AERO TECH','ROOM 1801-1809 No. 145 PUJIAN ROAD, QIANGSHENG PLAZA, PUDONG DISTRICT', 'SHANGHAI P.R.', 'CHINA', '+8602168381181	', NULL,'BAOPENG LIU');

-- ************************************************************************************************ --
-- ----------------------------- Test Data -------------------------------------------------------- --
-- ************************************************************************************************ --

-- Generic test entities
INSERT INTO `T_GENERIC_AIRCRAFT` (`GA_ID`,`GA_NAME`,`GA_CONSTRUCTOR`,`GA_TYPE`) VALUES /* Helico 1 - 1 */
(NULL,'Apache','Airbus','helico');
INSERT INTO `T_GENERIC_AIRCRAFT` (`GA_ID`,`GA_NAME`,`GA_CONSTRUCTOR`,`GA_TYPE`) VALUES /* Helico 2 - 2 */
(NULL,'ArianoCopter','EuroCopter','helico');
INSERT INTO `T_GENERIC_AIRCRAFT` (`GA_ID`,`GA_NAME`,`GA_CONSTRUCTOR`,`GA_TYPE`) VALUES /* Engine 1 - 3 */
(NULL,'Motor-B4','Siemens','engine');
INSERT INTO `T_GENERIC_AIRCRAFT` (`GA_ID`,`GA_NAME`,`GA_CONSTRUCTOR`,`GA_TYPE`) VALUES /* Engine 2 - 4*/
(NULL,'AA-745','Dassault','engine');
INSERT INTO `T_MANUAL` (`M_ID`,`M_ID_GA`,`M_ID_MANUAL`,`M_NAME`,`M_REFERENCE`,`M_DESCRIPTION`) VALUES /* Manual 1 Helico 1 - 1 */
(NULL,1,NULL,'Apache-Rotor','Ap-M-01','Apache rotor');
INSERT INTO `T_MANUAL` (`M_ID`,`M_ID_GA`,`M_ID_MANUAL`,`M_NAME`,`M_REFERENCE`,`M_DESCRIPTION`) VALUES /* Manual 2 Helico 1 - 2 */
(NULL,1,NULL,'Apache-Body','Ap-M-02','Apache body');
INSERT INTO `T_MANUAL` (`M_ID`,`M_ID_GA`,`M_ID_MANUAL`,`M_NAME`,`M_REFERENCE`,`M_DESCRIPTION`) VALUES /* Manual 1 Helico 2 - 3 */
(NULL,2,NULL,'Ariano-Bell','Ar-M-03','Ariano bells');
INSERT INTO `T_MANUAL` (`M_ID`,`M_ID_GA`,`M_ID_MANUAL`,`M_NAME`,`M_REFERENCE`,`M_DESCRIPTION`) VALUES /* Manual 2 Helico 2 - 4 */
(NULL,2,NULL,'Ariano-body','Ar-M-04','Ariano body');
INSERT INTO `T_MANUAL` (`M_ID`,`M_ID_GA`,`M_ID_MANUAL`,`M_NAME`,`M_REFERENCE`,`M_DESCRIPTION`) VALUES /* Manual 1 Engine 1 - 5 */
(NULL,3,NULL,'Engine67-guid','E68-M-01','motor user guid');
INSERT INTO `T_MANUAL` (`M_ID`,`M_ID_GA`,`M_ID_MANUAL`,`M_NAME`,`M_REFERENCE`,`M_DESCRIPTION`) VALUES /* Manual 1 Engine 2 - 6 */
(NULL,4,NULL,'Engine87-guid','E87-M-01','motor user guid');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 1 M 1 H 1 - 1 */
(NULL,1,'24.0.0','Stuff to do');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 2 M 1 H 1 - 2 */
(NULL,1,'35.0.0','Stuff to do');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 3 M 1 H 1 - 3 */
(NULL,1,'25.0.0','Stuff to do');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 4 M 1 H 1 - 4 */
(NULL,1,'45.0.0','Stuff to do');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 1 M 2 H 1 - 5 */
(NULL,2,'12.0.0','Stuff to do');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 2 M 2 H 1 - 6 */
(NULL,2,'8.0.0','Stuff to do');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 3 M 2 H 1 - 7 */
(NULL,2,'9.0.0','Stuff to do');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 1 M 1 H 2 - 8 */
(NULL,3,'11.0.0','Stuff to do');
INSERT INTO `T_GENERIC_SUB_TASK` (`GST_ID`,`GST_ID_M`,`GST_NUMBER`,`GST_DESCRIPTION`) VALUES /* ST 2 M 1 H 2 - 9 */
(NULL,4,'7.0.0','Stuff to do');
INSERT INTO `T_GENERIC_PART` (`GP_ID`,`GP_NUMBER`,`GP_NAME`,`GP_TYPE`,`GP_LOCATION`,`GP_DESCRIPTION`) VALUES
(NULL,'15484','Candel','Part','Hangar','Motor Part');
INSERT INTO `T_LINK_GP_GST` (`LGG_ID`,`LGG_ID_GP`,`LGG_ID_GST`, `LGG_QTY`) VALUES
(NULL, 1, 1, 5);

-- Project test entities
INSERT INTO `T_ENGINE` (`E_ID`,`E_ID_GA`,`E_ID_LOG_BOOK`,`E_SERIAL`,`E_NAME`,`E_TYPE`,`E_TIME`) VALUES
(NULL,3,NULL,'M-6875','Motor-475','Engine',1200);
INSERT INTO `T_ENGINE` (`E_ID`,`E_ID_GA`,`E_ID_LOG_BOOK`,`E_SERIAL`,`E_NAME`,`E_TYPE`,`E_TIME`) VALUES
(NULL,4,NULL,'M-8754','Motor-789','Engine',1200);
INSERT INTO `T_HELICOPTER` (`H_ID`,`H_ID_GA`,`H_ID_E1`,`H_ID_E2`,`H_ID_LOG_BOOK`,`H_ID_STATUS_SHEET`,`H_SERIAL`,`H_TIME`,`H_LANDING`) VALUES
(NULL,1,1,2,NULL,NULL,'WTF-4587',1200,800);
INSERT INTO `T_CUSTOMER` (`C_ID`,`C_NAME`,`C_PHONE`,`C_MAIL`) VALUES
(NULL,'Michel','+60 1 00 00 00 00','michel.dupont@mail.com');
INSERT INTO `T_PROJECT` (`P_ID`,`P_ID_C`,`P_ID_H`,`P_NAME`,`P_OPENED_DATE`,`P_CLOSED_DATE`) VALUES
(NULL,1,1,'145','2017-02-08',NULL);

-- Project test elements
INSERT INTO `T_WORK_ORDER` (`WO_ID`,`WO_ID_H`,`WO_NAME`,`WO_OPENED_DATE`,`WO_CLOSED_DATE`) VALUES
(NULL,1,'145-%DOC%-2017/06/05-Michel-WTF-4587','2017-02-08',NULL);
INSERT INTO `T_SUB_TASK` (`ST_ID`,`ST_ID_WO`,`ST_ID_GST`,`ST_ID_U_PERFORMER`,`ST_ID_U_RELEASER`,`ST_REFERENCE`,`ST_WORK_REQUIRED`,`ST_RECTIFICATION_DETAILS`,`ST_IN_SOW`,`ST_APPROVED_DATE`,`ST_PERFORM_DATE`,`ST_RELEASE_DATE`,`ST_PRICE_QUOTE`, `ST_ACCURRENCY`) VALUES
(NULL,1,1,NULL,NULL,'24-R-87','Do stuff here again','Nothing','yes',NULL,NULL,NULL,NULL,NULL);

-- Other entities
INSERT INTO `T_USER` (`U_ID`,`U_NAME`,`U_PASSWORD`,`U_STATUS`,`U_CODE`) VALUES
(NULL,'Victor','76289356c8946cfc9261340f1d15181b6b06147b',4,'45876');
INSERT INTO `T_USER` (`U_ID`,`U_NAME`,`U_PASSWORD`,`U_STATUS`,`U_CODE`) VALUES
  (NULL,'Justine','0250a7b095bc6a969adbe25de14d23c4224d37c3',4,NULL);
INSERT INTO `T_STOCK` (`S_ID`,`S_ID_GP`,`S_ID_PURCHASE_ORDER`,`S_ID_ARC`,`S_SERIAL`,`S_ARC_NAME`,`S_PO_NAME`,`S_QUANTITY_IN`,`S_QUANTITY_NUMBER`,`S_RECEIVED`,`S_RECEIVED_DATE`,`S_EXPIRATION_DATE`,`S_PRICE`,`S_ACCURENCY`,`S_VENDOR`,`S_COMMENT`) VALUES
(NULL,1,NULL,NULL,NULL,'ARC-7845','PO-4455',1,1,'yes','2017-02-08','2018-02-08',100.10,'RM','AirBoat','Super piece');
INSERT INTO `T_PROJECT_PART` (`PP_ID`,`PP_ID_ST`,`PP_ID_GP`,`PP_ID_USER`,`PP_IPC`,`PP_STATUS`,`PP_VALIDATED`,`PP_QUANTITY_REQUESTED`,`PP_REQUESTED_DATE`) VALUES
(NULL,1,1,1,'Super Tache','required',DEFAULT,1,'2017-03-09');
INSERT INTO `T_LINK_PP_S` (`LPS_ID`,`LPS_ID_PP`,`LPS_ID_S`,`LPS_QUANTITY_NUMBER`,`LPS_DATE_OUT`) VALUES
(NULL,1,1,1,'2017-05-23');

-- Management
INSERT INTO `T_RECORDED_WORK` (`RW_ID`, `RW_ID_ST`, `RW_DESCRIPTION`, `RW_TOTAL_MIN`) VALUES
  (NULL, NULL, 'Clean Hangar', DEFAULT);
INSERT INTO `T_USER_WORK` (`UW_ID`, `UW_ID_RW`, `UW_ID_U`, `UW_DATETIME_BEGIN`, `UW_DATETIME_END`, `UW_TOTAL_MIN`) VALUES
  (NULL, 1, 1, CURRENT_TIMESTAMP, DEFAULT, DEFAULT);